sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc
env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
    - CI_ROS_DISTRO="indigo"
    - PACKAGE_NAME=atf_test
    - REPO_NAME=masterarbeit
    - ROBOT=cob4-2
    - ROBOT_ENV=empty
#  matrix:
#    - CI_ROS_DISTRO="indigo"
#    - CI_ROS_DISTRO="jade"
install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-catkin-tools python-wstool python-ros*
  - sudo rosdep init
  - rosdep update

  - rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  
  - mkdir -p $CATKIN_WS_SRC
  - ln -s $TRAVIS_BUILD_DIR $CATKIN_WS_SRC
  - cd $CATKIN_WS_SRC
  - catkin_init_workspace
  - wstool init
  - wstool merge -y https://raw.githubusercontent.com/ipa320/setup/master/repositories/cob_indigo_bringup.rosinstall
  - wstool update
  - git clone https://github.com/ipa320/cob_manipulation.git
  - git clone https://github.com/koellsch/atf.git
  - rm -rf masterarbeit/cob_grasping_app
  - sudo rosdep init
  - rosdep update
  - cd $CATKIN_WS
  - rosdep install --from-paths src -i -y
  - catkin_make
  - source $CATKIN_WS/devel/setup.bash

script:
  - sudo apt-get install ros-indigo-rosbridge-suite python-dev gcc python-pip curl
  - sudo pip install psutil
  - cd $CATKIN_WS
  - catkin_make test --force-cmake --pkg $PACKAGE_NAME
  - cd $CATKIN_WS_SRC/$REPO_NAME/$PACKAGE_NAME/scripts
  - ./dropbox_uploader.sh upload ../results/* .
  # - catkin init
  # Enable install space
  #- catkin config --install
  # Build [and Install] packages
  #- catkin build --limit-status-rate 0.1 --no-notify -DCMAKE_BUILD_TYPE=Release
  # Build tests
  #- catkin build --limit-status-rate 0.1 --no-notify --make-args tests
  # Run tests
  #- catkin run_tests
