path_length:
  topics:
    - "/tf"
obstacle_distance:
  services:
    - "/atf/get_obstacle_distance"
  robot_description: ""
robot_bringup_launch: ""
wait_for_topics: []
wait_for_services: []
additional_parameter: []
additional_arguments: []