# Definition of various test suites
testsuite_1:
  scene_config:                 # You have to define at least one scene name
    - "scene_1"
    - "scene_2"
    - "scene_3"
  test_config:                  # You have to define at least one test name
    - "test_1"
    - "test_2"
  robot:                        # You have to define at least one robot name
    - "cob4-2"
  planer_id:                    # Other parameters can be defined at will
    - "SBLkConfigDefault"
    - "ESTkConfigDefault"
    - "LBKPIECEkConfigDefault"
    - "BKPIECEkConfigDefault"
    - "KPIECEkConfigDefault"
    - "RRTkConfigDefault"
    - "RRTConnectkConfigDefault"
    - "RRTstarkConfigDefault"
    - "TRRTkConfigDefault"
    - "PRMkConfigDefault"
    - "PRMstarkConfigDefault"
  planning_method:
    - "cartesian"
  jump_threshold:
    - 2
  eef_step:
    - 0.01