bagfile_output: "atf_recorder/data/"                                 # Folder for bagfile output
test_suite_file: "atf_app_template/config/test_suite.yaml"   # Path of the test_suite file
test_config_file: "atf_app_template/config/test_config.yaml" # Path of the test_config file
robot_config_path: "atf_app_template/config/"                        # Folder which contains the robot_config files

result_json_output: "atf_presenter/data/"                            # Folder for the json files output
result_yaml_output: ""                                               # Folder for the yaml files output

test_application_path: "atf_app_template/test/atf_app.test"          # Path of the application test file
additional_launch_file: "atf_app_template/launch/atf_app.launch"     # Path of the additional launch file

time_limit: 500.0                                                    # Time limit in seconds (travis-ci has a maximum of 600s after which it will end the building process)
test_repetitions: 5                                                  # Number of repetitions per test