test_1:
  all:
    time:
    publish_rate:
      topics:
        - "/tf"
        - "/test"
      hz:
        - 300
        - 100
      error:
        - 10
        - 10
  test1:
    time:
    path_length:
      - [world, reference1]

  test2:
    time:
    path_length:
      - [world, reference1]

  test3:
    time:
    path_length:
      - [world, reference1]
