test_1:
  all:
    time:
    path_length:
      - [world, reference1]
  test1:
    time:
    path_length:
      - [world, reference2]

  test2:
    time:
    resources:
      cpu: [rostest, atf_status_server]
      mem: [rostest, atf_status_server]
    path_length:
      - [world, reference1]
      - [world, reference2]
      - [world, reference3]

  test3:
    time:
    resources:
      cpu: [rostest, atf_status_server]
      mem: [rostest, atf_status_server]
      io: [rostest, atf_status_server]
      network: [rostest, atf_status_server]
    path_length:
      - [world, reference4]
      - [reference1, reference4]
