test_1:
  all:
    time:
  test1:
    time:
    path_length:
      - [world, reference1]

  test2:
    time:
    path_length:
      - [world, reference1]

  test3:
    time:
    path_length:
      - [world, reference1]
