bagfile_output: "atf_recorder/data/"
test_suite_file: "cob_grasping_app/config/test_suite.yaml"
test_config_file: "cob_grasping_app/config/test_config.yaml"
robot_config_path: "cob_grasping_app/config/"

result_json_output: "atf_presenter/data/"
result_yaml_output: ""

test_application_path: "cob_grasping_app/test/grasping_app.test"
additional_launch_file: "cob_grasping_app/launch/move_group.launch"

time_limit_recording: 240.0
time_limit_analysing: 350.0
test_repetitions: 2