test_1:
  planning:
    time:
    resources:
      cpu: [move_group]
      mem: [move_group]
      io: [move_group]
      network: [move_group]

  execution:
    time:
    resources:
      cpu: [move_group, rostest]
      mem: [move_group, rostest]
      io: [move_group, rostest]
      network: [move_group, rostest]
    path_length:
      - [base_link, gripper_right_grasp_link]
    obstacle_distance:
      - [gripper_right_grasp_link]
