path_length:                                          # Topics for the metric 'path_length'
  topics:
    - "tf topic name"
obstacle_distance:                                    # Topics for the metric 'obstacle_distance'. Do not alter!!!
  topics:
    - "/atf/obstacle_distance"
  robot_description: "name of robot description"      # Name of the robot description
robot_bringup_launch: "robot bringup launch"          # Path to the robot bringup launch file
wait_for_topics: ["topic1 name", "topic2 name"]       # Names of the topics to wait for before beginning the test
wait_for_services: ["service1 name", "service2 name"] # Names of the services to wait for before beginning the test