path_length:
  topics: ["tf topic name"]
obstacle_distance:
  topics: ["/atf/obstacle_distance"]
robot_bringup_launch: "robot bringup launch"
wait_for_topics: ["topic1 name", "topic2 name"]
wait_for_services: ["service1 name", "service2 name"]